### ISSUE TITLE
gmaps iframe not working as expected

### ISSUE THREAD

**Issue by laurafitzgerald** [laurafitzgerald/coderdojo#4]
@wtrocki could you take a look at this please
The steps i took were 
- go to googlemaps
- search arc labs
- take (what I think is) the pb param from the url
- replace in the iframe
- error showing now:
`The Google Maps API server rejected your request. Invalid request. Invalid 'pb' parameter.`
cc @mathana96

**Comment by laurafitzgerald** [comment]
@wtrocki on my own machine so no slack

**Comment by laurafitzgerald** [comment]
@wtrocki you can ignore this one. looks like @mathana96 solved it and will open pr.

**Comment by wtrocki** [comment]
Best to replace entire embed tag. You can get that directly from google maps

**Comment by laurafitzgerald** [comment]
Closing as solved in [this pr](https://github.com/laurafitzgerald/coderdojo/pull/5)
